name: Java CI with Gradle

on:
  push:
   # branches: [ "main" ]
  pull_request:
   # branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    # permissions:
    #   contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 20
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'temurin'
    # - name: Setup Gradle
    - uses: gradle/actions/setup-gradle@v3 # v3.0.0
      with:
        gradle-version: 8.6
    # - name: Build with Gradle Wrapper
    #   run: ./gradlew build
    - run: ./gradlew checkstyleMain
      working-directory: ./app
    # - run: ./gradlew test
