name: Java CI with Gradle

on:
  - push
  - pull_request
  
#defaults:
#  run:
#    working-directory: ./app


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle Wrapper
      run: ./gradlew build
      working-directory: ./app
    
  code-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v5.0.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CdCl_TEST_REPORTER_ID}}
        JACOCO_SOURCE_PATH: ./app/src/main/java
      with:
        #workingDirectory: /home/runner/work/java-project-71/java-project-71/app
        coverageCommand: make report
        coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
